DROP TABLE IF EXISTS TB_HEROS;
--create
CREATE TABLE TB_HEROS (
ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
NAME VARCHAR(255) NOT NULL,
POWER VARCHAR(255) NOT NULL
);
INSERT INTO TB_HEROS (NAME, POWER)
VALUES
  ('Flash', 'valocity'),
  ('Aquaman','speak with animals'),
  ('Batman', 'money');
--read
SELECT * FROM TB_HEROS;
SELECT * FROM TB_HEROS WHERE NAME= 'Flash';
--update
UPDATE TB_HEROS
SET NAME = 'Goku', POWER='GOD'
WHERE ID= '1'
--delete
DELETE FROM TB_HEROS WHERE ID= '2';
